# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d6d7c6257df9c1ea077e4f1bd204faf6bdb12979eca0ec3ffb1dcd50c989fc5d0ef26e8c35cb86874361a1d19c73b557b66abe846a711db470509a530392e3e

test:
  secret_key_base: 604e9c88d5fc5658cfd99ef36faf4158fa777a7b98458a25cf0b8b9268218bc6be281dc9d73c7d91d01c54685e6f27bd020ef575c17d726f6c292957344b21a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
